version: "3.9"

services:
  backend:
    container_name: docker_project_ngcash
    build: 
      dockerfile: Dockerfile
      context: "./back-end"
    ports:
      - 3000:3000
    depends_on:
      - postgres
    command: bash -c "yarn typeorm migration:run -d src/data-source && yarn dev"
    volumes:
      - /app/node_modules
      - ./back-end:/app

  frontend:
    container_name: docker_project_ngcash
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: "./front-end"
    volumes:
      - /app/node_modules
      - ./front-end:/app
    ports:
      - 5173:5173

  postgres:
    container_name: db_project_ngcash
    image: postgres:latest
    ports:
      - 5434:5432
    env_file:
      - ./back-end/.env
